name: 非常自信
description: 在通往牛逼的路上大步向前
meta_description: ""

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 5
baseurl: /
domain_name: 'http://nsmutablearray.github.io'
google_analytics: ''

# Markdown render redcarpet options
redcarpet:
  extensions: ["hard_wrap", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "superscript","underline"]

# Details for the RSS feed generator
url:            'http://nsmutablearray.github.io'
author:         '非常自信'
